// SPDX-License-Identifier: MIT
pragma solidity 0.8.6;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts@4.6.0/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts@4.6.0/utils/Counters.sol";

contract keeperDress is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter public tokenIdCounter;
 
   // Metadata information for each stage of the NFT on IPFS.

   // En este reto decidí crear un NFT que representa el certificado de propiedad o autenticidad
   //del vestido utilizado por Marilyn Monroe. El cambio de estado del mismo deja asentado
   //en cada uno de los archivos Json quienes fueron propietarios de la prenda a lo largo del tiempo.
    string[] IpfsUri = [
        "https://gateway.pinata.cloud/ipfs/QmVDQto4HY8vaK6sfqVtqWfP1CA6swuq7nSp48Hx8JHVMQ", 
        "https://gateway.pinata.cloud/ipfs/QmdANWKqGH3GqHfFidXNtsnUgfr9CyruoKbuAeCaZd7sBx",
        "https://gateway.pinata.cloud/ipfs/QmQpJzPByo2Kk717dFH2BoZ6TK2mqUYp6pxYLSC9N6dGsq",
        "https://gateway.pinata.cloud/ipfs/QmUn4ktztDyLTsmQrUo1EiWd6PKxkcaoUFiWMNxBVywCP6",
        "https://gateway.pinata.cloud/ipfs/QmTYHpkwY5k7X8VdAj6ZwSzZaNwECGK1q1MT6EJYrhDEuz"
    ]; 

    uint256 lastTimeStamp;
    uint256 interval;

  constructor(uint _interval) ERC721("Marilyn Monroe Dress", "MarMonDress") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
  }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory) {
        upkeepNeeded = (block.timestamp -lastTimeStamp) > interval;
        }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = tokenIdCounter.current() - 1;
            growDress(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, IpfsUri[0]);
    }

    function growDress(uint256 _tokenId) public {
        if(dressStage(_tokenId) >= 4){return;}
        // Get the current stage of the flower and add 1
        uint256 newVal = dressStage(_tokenId) + 1;
        // store the new URI
        string memory newUri = IpfsUri[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function dressStage(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // N01
        if (compareStrings(_uri, IpfsUri[0])) {
            return 0;
        }
        // N02
       if (
            compareStrings(_uri, IpfsUri[1]) 
        ) {
            return 1;
        }
        // Must be a Bloom
        //  N03
        if (
            compareStrings(_uri, IpfsUri[2]) 
        ) {
            return 2;
        }
        // N04
        if (
            compareStrings(_uri, IpfsUri[3]) 
        ) {
            return 3;
        }
        //N05
        return 4;
    }

    
    

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}